#!/bin/bash
PROTOBUF_SRC=protobuf-3.1.0-alpha-1.tar.gz

if [ ! -f "$PROTOBUF_SRC" ]; then
    echo "no src $PROTOBUF_SRC"
    curl -L https://github.com/google/protobuf/archive/v3.1.0-alpha-1.tar.gz -o protobuf-3.1.0-alpha-1.tar.gz
else
   echo "has src"
fi

tar xvf protobuf-3.1.0-alpha-1.tar.gz && cd protobuf-3.1.0-alpha-1 && ./autogen.sh 
./configure
make &&  make install

