spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.properties
              path: application.properties
      containers:
        ports:
          - containerPort: 8080
            name: web
          - containerPort: 7575
            name: grpc
      　volumeMounts:
          - name: config
            mountPath: /app/config

