spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.properties
              path: application.properties
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
        ports:
          - containerPort: 8080
            name: web
          - containerPort: 7575
            name: grpc-node
