# application properties
spring:
  datasource:
    name: testdb
    url: jdbc:mysql://172.16.45.3:3306/vp_common_config?useUnicode=true&characterEncoding=utf-8
    username: ipservice
    password: 'mQO7NpV1ohNjA37/xSIsNCIlVY4woR+zuAyeD3dBPpwcUX75gsZbvJftqhtpESDvItn6MUlJwrAAsi5+65fySQ=='
    # using druid data source
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 600000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # encrypt password
    filters: config,stat,wall,log4j
    connectionProperties: "config.decrypt=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
    useGlobalDataSourceStat: true

  data:
    mongodb:
      host: 172.16.45.3
      port: 27017

  redis:
    database: 0
    host: 172.16.45.3
#    password: 'traffic.prod'
    port: 6379
    timeout: 3000000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  cache:
    type: redis
spring.application.name: ipservice
spring.sleuth.sampler.percentage: 1.0
#spring.sleuth.integration.enabled: false
ipservice.message: 'heheda,spring cloud kubernetes from here !! 1110'

# LOGGING
logging:
  level:
    tk.mybatis: DEBUG
druid:
  allow: ""
  deny: "172.16.0.122"
  loginUsername: vpclub
  loginPassword: vpclub.pub