spring.application.name: ipservicedemo
spring.sleuth.sampler.percentage: 1.0
# application properties
app:
  datasource:
    name: vp_common_config
    host: 172.16.2.231:3306
    username: root
    password: W9ci2t3etu51StgDvtARiCAUGXIDSiwiFaATxcrMoZcDNUc65Z25g/vo1AUgH3fg+bu7NK7hCv3g/19R0M7lAQ==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJEF9SzddgYHPiMKHbWtos7KBxj1tUO19Ro8CkB76TbsHKhfqcLU4hi8VDpTelF52YmKEDMPcM0uWgRBIkqy+kcCAwEAAQ==
spring:
  # 数据库配置
  datasource:
    name: ${app.datasource.name}
    url: jdbc:mysql://${app.datasource.host}/${app.datasource.name}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      # encrypt password
      filters: config,stat,wall,log4j
      connection-properties: "config.decrypt=true;config.decrypt.key=${app.datasource.druid.public-key};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
      use-global-data-source-stat: true

  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

  cache:
    type:  hazelcast

mybatis:
  config-location : "classpath:mybatis-config.xml"
  #checkConfig-location : false
  mapper-locations : "classpath:mapper/*Mapper.xml"

hazelcast:
  enabled: true
  cluster: true
  servers:
    -  hazelcast.hazelcast-cluster.svc.cluster.local:5701
#kafka
kafka:
  broker: kafka.kafka.svc.cluster.local:9092
  topic: topic1
  group: si.group
  partions: 6
  timeout: 15000

ipservice.message: 'heheda,spring cloud kubernetes from here !! 1110'
# LOGGING
logging:
  level:
    tk.mybatis: DEBUG
cors:
  mappings: /**
  allowedOrigins:
