
# application properties
app:
  datasource:
    name: vp_common_config
    host: 172.16.2.231:3306
    username: root
    password: W9ci2t3etu51StgDvtARiCAUGXIDSiwiFaATxcrMoZcDNUc65Z25g/vo1AUgH3fg+bu7NK7hCv3g/19R0M7lAQ==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJEF9SzddgYHPiMKHbWtos7KBxj1tUO19Ro8CkB76TbsHKhfqcLU4hi8VDpTelF52YmKEDMPcM0uWgRBIkqy+kcCAwEAAQ==

hazelcast:
  enabled: false
  cluster: true
  servers:
    -  172.16.5.40:5701

spring.sleuth.sampler.percentage: 1.0

#dev mode disable zipkin
spring.cloud.kubernetes.zipkin.discovery.enabled: false
ipservice.message: 'heheda,spring cloud kubernetes from here !! 1110'

#kafka
kafka:
  broker: 172.16.5.23:9092
  topic: topic1
  group: si.group
  partions: 6
  timeout: 15000


