# application properties
app:
  datasource:
    name: vp_common_config
    host: 172.16.5.23:3306
    username: ipservicedemo
    password: UFeMDFM7e1Tw9pPrxCVhgpuFgvbbC3WiKffh+ekbxVD5gXn4I4MyZR3HoAdP3fYmjvpr096frbhKNeL/GnwZ2Q==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI2zXImQtSctT1r23Qdk05CL/CnAyprxOX6bWy8wo9RQAjJ672SPcvZxnXQTom6DteYQ5D6oSFa+atEXXlp9doECAwEAAQ==

hazelcast:
  enabled: false
  cluster: true
  servers:
    -  172.16.5.40:5701

spring.sleuth.sampler.percentage: 1.0

#dev mode disable zipkin
spring.cloud.kubernetes.zipkin.discovery.enabled: false
ipservice.message: 'heheda,spring cloud kubernetes from here !! 1110'

#kafka
kafka:
  broker: 172.16.5.23:9092
  topic: topic1
  group: si.group
  partions: 6
  timeout: 15000
