package cn.vpclub.ipaddress.storage.mapper;

import cn.vpclub.ipaddress.api.domain.Sequences;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface SequencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequences
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequences
     *
     * @mbggenerated
     */
    int insert(Sequences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequences
     *
     * @mbggenerated
     */
    int insertSelective(Sequences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequences
     *
     * @mbggenerated
     */
    Sequences selectByPrimaryKey(Integer id);

    List<Sequences> selectAllData();

    /**
     * 根据序列类型查询序列信息
     *
     * @param seqType 序列类型1：订单  2：机构
     * @return Sequences
     */
    Sequences selectBySeqType(@Param("seqType") Integer seqType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequences
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sequences record);

    /**
     * 修改序列首位数字值
     *
     * @param record
     * @return Integer
     */
    Integer updateNumberPrefix(Sequences record);

    /**
     * 修改序列位数值
     *
     * @param record
     * @return Integer
     */
    Integer updateDigitValue(Sequences record);

    /**
     * 修改序列当前值
     *
     * @param record
     * @return Integer
     */
    Integer updateCurrentValue(Sequences record);
}