package cn.vpclub.api.domain;

import java.io.Serializable;

public class Sequences implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.seqtype
     *
     * @mbggenerated
     */
    private Integer seqtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.currentno
     *
     * @mbggenerated
     */
    private Long currentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.digit
     *
     * @mbggenerated
     */
    private Integer digit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.number_prefix
     *
     * @mbggenerated
     */
    private Integer numberPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.countnum
     *
     * @mbggenerated
     */
    private Integer countnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequences.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.id
     *
     * @return the value of sequences.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.id
     *
     * @param id the value for sequences.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.seqtype
     *
     * @return the value of sequences.seqtype
     *
     * @mbggenerated
     */
    public Integer getSeqtype() {
        return seqtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.seqtype
     *
     * @param seqtype the value for sequences.seqtype
     *
     * @mbggenerated
     */
    public void setSeqtype(Integer seqtype) {
        this.seqtype = seqtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.currentno
     *
     * @return the value of sequences.currentno
     *
     * @mbggenerated
     */
    public Long getCurrentno() {
        return currentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.currentno
     *
     * @param currentno the value for sequences.currentno
     *
     * @mbggenerated
     */
    public void setCurrentno(Long currentno) {
        this.currentno = currentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.digit
     *
     * @return the value of sequences.digit
     *
     * @mbggenerated
     */
    public Integer getDigit() {
        return digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.digit
     *
     * @param digit the value for sequences.digit
     *
     * @mbggenerated
     */
    public void setDigit(Integer digit) {
        this.digit = digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.number_prefix
     *
     * @return the value of sequences.number_prefix
     *
     * @mbggenerated
     */
    public Integer getNumberPrefix() {
        return numberPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.number_prefix
     *
     * @param numberPrefix the value for sequences.number_prefix
     *
     * @mbggenerated
     */
    public void setNumberPrefix(Integer numberPrefix) {
        this.numberPrefix = numberPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.countnum
     *
     * @return the value of sequences.countnum
     *
     * @mbggenerated
     */
    public Integer getCountnum() {
        return countnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.countnum
     *
     * @param countnum the value for sequences.countnum
     *
     * @mbggenerated
     */
    public void setCountnum(Integer countnum) {
        this.countnum = countnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequences.remark
     *
     * @return the value of sequences.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequences.remark
     *
     * @param remark the value for sequences.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}